[package]
name = "vetkd_system_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8.4"
ic-cdk = "0.7.1"
serde = "1"
ic-crypto-internal-bls12-381-type = { git = "https://github.com/dfinity/ic" }
ic_bls12_381 = { version = "0.7.1", default-features = false, features = ["groups", "pairings", "alloc", "experimental", "zeroize"] }
zeroize = { version = "1", features = ["zeroize_derive"] }
rand = "0.8"
rand_chacha = "0.3"
sha3 = "0.9"
lazy_static = "1.4"
hex = "0.4"